version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: antoine
      POSTGRES_PASSWORD: genonceau
      POSTGRES_DB: terragrow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: back
    container_name: back
    environment:
      DATABASE_URL: postgres://antoine:genonceau@postgres:5432/terragrow
      STANDARD_BAND_WIDTH: 2.5
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  front:
    build:
      context: front
    container_name: front
    ports:
      - "4200:4200"

volumes:
  postgres-data: